### PR TITLE
Add error handling to mark the action as failed when it fails

### PR DESCRIPTION
**Pull request by devlato**
Adding error handling, as per the [documentation](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action)

### CODE REVIEW

**Comment by devlato** [comment]
@kt3k hey mate, mind having a look?

**Comment by kt3k** [comment]
The error handling looks good to me, but I think we need to keep `node_modules`. ref: https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github

**Comment by devlato** [comment]
@kt3k oh right, interesting! Will update shortly

**Comment by devlato** [comment]
@kt3k done ✅

**Comment by devlato** [comment]
@kt3k are you fine with it? Could you merge it and tag a release?

**Review by kt3k — APPROVED** [review]
LGTM. Thank you for your contribution!

**Comment by devlato** [comment]
@kt3k thanks! Please let me know if you find any issues

**Comment by devlato** [comment]
@kt3k btw could you please [publish it](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace) to the marketplace? I think the last publicly available tagged one is still `v1.0.0`

Screen Shot 2021-11-18 at 14 47 26

**Comment by kt3k** [comment]
Oh, I didn't realize that. Updated.

**Comment by devlato** [comment]
@kt3k thanks!

**Pull request merged**
